### ISSUE TITLE
--format fuubar does not work but --format Cucumber::Formatter::Fuubar does

### ISSUE THREAD

**Issue by grosser** [martinciu/fuubar-cucumber#14]
```
cucumber --format fuubar features/xx.feature
Using the default profile...
WARNING: No DRb server is running. Running features locally:
wrong constant name fuubar
Error creating formatter: fuubar (NameError)
```

(whith does not work I mean: "Does not work in our maybe strange setup")
(that is after adding require 'cucumber/formatter/fuubar' to env.rb)

please either fix this or document in the readme

**Comment by an0nym0use** [comment]
I had the same issue, and remedied it with the solution from @abotalov

fuubar (1.1.0)
fuubar-cucumber (0.0.18)
cucumber (1.2.1)
cucumber-rails (1.3.0)
